services:

  stor_backend:
    container_name: stor_backend
    build:
      context: ./StoR_backend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./StoR_backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      database:
        condition: service_healthy
    networks:
      - stor_network
  
  database:
    image: postgres:16
    restart: unless-stopped
    container_name: database
    env_file: .env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - stor_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pg-admin
    env_file: .env
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - stor_network
    depends_on:
      - database

networks:
  stor_network:
    driver: bridge

volumes:
  node_modules: {}
  postgres_data:
